
emrakul = "Emrakul is the Titan of Corruption, the largest and most fearsome of the Eldrazi.",
"She does not affect inorganic matter - rocks, water, etc.",
"- but twists all things living, be they plants, animals, or other sentient beings.",
"She causes silent terror wherever she soars, embodying desolation, emotional and physical distance,",
"the chill of the void, and the terror of being alone. According to Gideon Jura, she is 150 feet tall.",
"The Emrakul lineage is characterized by flesh-like lattice structures, uneasy bilateral symmetry,",
" and tentacles that end in knobby, vestigial digits. Looking like spongy, alien baleen,",
" the lattice respires independent of the Eldrazi herself, supporting a host of unseen mite creatures within.",
" Some within this lineage, including Emrakul herself, float above the ground,",
" using unknown powers to alter the surrounding gravity."

kozilek = "Kozilek(KOH-zih-lek), the Butcher of Truth is one of the three Eldrazi titans and",
" the inspiration for the Zendikari merfolk god Cosi and the Kore god Talib",
" Kozilek is the Titan of Distortion, a reality-slicing nightmare of relentless insanity.",
" He changes the perception of reality, making it impossible to discern the truth.",
" He twists loyalties, muddies thoughts, transforms emotions and induces despair and panic.",
" Kozilek represents themes of deception, puzzles, lies, mental domination, transformation,",
" and experimentation. Sages call Kozilek the confusion of panic, the trap of enigmas,",
" and the harrower of thought.  Eldrazi of the Kozilek brood lineage possess many eyes",
" growing near joints or along body ridges, jagged plates or blades of lustrous black mineral",
" jutting from or floating around their bodies, and animalistic or insectoid anatomies covered",
" in tough carapaces. Kozilek's drones can absorb life just by their presence but prefer",
" to rend flesh with their onyx-like projections."

ulamog = "Ulamog, the 'Infinite Gyre' is one of the three Eldrazi titans",
" and the monstrosity whose half-forgotten name came to be known as the Zendikari merfolk sea god Ula.",
" Ulamog is the Titan of Consumption, as he and his brood consume living and unliving matter alike.",
" In doing so, they drain mana and vital energy from everything in the vicinity.",
" His processors transform the consumed energy into spell-like effects that defy",
" the understanding of Zendikari mages, creating plagues, deadly parasites, and endless teeming spawn.",
" The processors leave distinctive white, chalky lattice-like structures in their wake.",
" Everything, including water, is transformed into a white manaless husk of what it once was.",
" Ulamog is emblematic of plague, the blind bonds between parasite and host, and overabundance;",
" he is creation and destruction wrapped together in unholy harmony."

eldrazi = { "Emrakul" : {
                    "card": "the aeons torn",
                    "lore": emrakul,
                },
                "Kozilek" : {
                        "card": "the great distortion",
                        "lore": kozilek,
                },
                "Ulamog" : {
                        "card": "the Ceaseless Hunger",
                        "lore": ulamog,
                },
        }








jace = "Jace Beleren is a compleated human planeswalker and mind-mage from Vryn.",
" While working with the Infinite Consortium on Ravnica, he went by the name Berrim.",
" He is the former Living Guildpact of Ravnica and a founding member of the Gatewatch.",
" He was compleated during the events of Phyrexia: All Will Be One."

gideon = "Gideon Jura, born Kytheon Iora, was a hieromancer and a member of Gatewatch.",
" Affectionately called Gids by Chandra Nalaar and called Beefslab by Liliana Vess.",
" although he is one of the most important planeswalkers he is most known for the fact the died",
" during the war of the spark on ravinca he sacrificied himself so that he would die,",
" instead of lilliana vess when she broker her demonic contract and went against nicol bolas's orders"

chandra = "Chandra Nalaar is a human planeswalker from Kaladesh. She is a member of the Gatewatch.",
" Chandra is a pyromancer knowns for taking out two of the three eldrazi titans in a blaze of fire,",
" as well as being an ingenius spellcaster even among the planeswalkers.",
" Although hotheaded she cares deeply for those she calls her friends."

nissa = "Nissa Revane is a Joraga Zendikari elf and former planeswalker,","who wields magic to muster elves and elementals and amplify their might.",
" She was a member of the Gatewatch, before she was compleated during the events of Phyrexia: All Will Be One.",
" At the end of New Phyrexia's Invasion of the Multiverse, she was un-compleated,",
" and subsequently lost her spark as part of the consequences of the invasion."

liliana = "Liliana Vess is a human planeswalker from Dominaria and is both a master necromancer and a healer.",
" For a while, she was dead to the Multiverse, her survival known only to select members of the Gatewatch.",
" Having freed herself from all her demonic contracts as well as from the Onakke Chain Veil,"
" she relocated to Fiora where she temporarily lived under the alias Ana Iora.",
" On Arcavios she was originally known as Professor Serafina Onyx, before reclaiming her original name,",
" and began taking steps to reclaim her ancestral Dominarian home. The Raven Man affectionally calls her Lili."



gatewatch = {"Jace Beleren" :{
    "card" : "Arcane strategist",
    "lore" : jace,
    },
        "Gideon Jura":{
            "card" : "Champion of Justice",
            "lore" : gideon,
        },
        "Chandra Nalar":{ 
        "card" : "Bold Pyromancer",
        "lore" : chandra,
        },
        "Nissa Revnae" :{
        "card" : "Natures Artisan",
        "lore" : nissa
        },
        "Liliana Vess" :{ 
        "card" : "Defiant Necromancer",
        "lore" : liliana,
        },                         
}




elesh_Norn = "Elesh Norn, was the Praetor of the white-aligned Machine Orthodoxy,",
" which led New Phyrexia. She is called The Mother of Machines,",
" Grand Praetor, or Grand Cenobite by her followers. At the end of New Phyrexia's Invasion",
" of the Multiverse, she was killed by Karn. Elesh Norn had a very tall,",
" almost skeletally thin humanoid figure. Her body was composed of red sinuous flesh",
" and white metallic porcelain. Her eyeless face carried a broad shield-like body visor.",
" Her mouth is filled with needle-like teeth. Elesh Norn led the Machine Orthodoxy.",
" She was an arrogant master manipulator who devoutly believed in her rhetoric",
" and did not like to be questioned. She was a fascist, theocratic dictator",
" who designed monuments in her image. Although she worked with the other praetors,",
" she wanted to be the one leading the charge. Elesh Norn designed grand plans",
" for all of Phyrexia and wrote the Argent Etchings, scriptures for her followers.",
" When the Phyrexians infected Mirrodin, it was a world of five suns, one for each of the five colors of Magic.",
" The five praetors each rose under the influence of a sun, with Elesh Norn emerging under the power of the White Sun.",
" Norn adopted human and elvish elements of culture. She was formed from the mana of Bringer, the white sun.",
" New Phyrexia's white-aligned faction, led by Norn, believes that Phyrexia must adhere to the teachings of the Father of Machines.",
" They intend to indoctrinate everyone about the truth, even if it means tearing them limb from limb",
" and reattaching the parts into a creation that is worthy of Phyrexia. They are dogmatic, hierarchical,",
" and orthodox in their methods. Norn appears on the surface to be delirious to some extent,",
" and her religious fanaticism has been interpreted as her being blind to the machinations of the other praetors.",
" She is a highly manipulative individual, subtly influencing her faction to suit her desires.",
" During Karn's reign as Father of Machines deep in the plane's core,",
" she even attempted to bring him to the surface to protect him from her fellow praetor, Jin-Gitaxias.",
" During the final battle in which the Phyrexians officially conquered Mirrodin, a Mirran angel named Atraxa was captured.",
" Elesh Norn was impressed by Atraxa's tenacity and 'rewarded' her with compleation, a process by which organic beings are converted into Phyrexians.",
" Elesh Norn's intent was for Atraxa to become the 'praetor's voice', a symbol of Phyrexia's unity.",
" Elesh Norn invited the other praetors to contribute, with only Urabrask declining.",
" Atraxa's creation marked the final victory of Phyrexia over Mirrodin."

vorinclex = "Vorinclex, called The Voice of Hunger, was the Green-aligned praetor of New Phyrexia.",
" Vorinclex stood twelve feet tall and his body was a raw pinkish-red color.",
" Across his shoulders he had a ruff of patchy fur in a dozen different hues swirled together.",
" Vorinclex's long and muscular arms ended in massive, curving talons with and two additional \nspindly arms extending from his chest.",
" His bone-colored head was a skull-like face flanked by razor tusks and broad, spined antlers. \nA social Darwinist,",
" he wished to make New Phyrexia a place hostile to sentience, which he despised, and based \nsolely on the roles of predator and prey,",
" of which only the strongest will survive. He ruled the Vicious Swarm as its apex predator. \nAlthough he was relatively intelligent,",
" he preferred making decisions with primal instinct and solving issues with brute strength and \nsharp fangs.",
" Vorinclex created new varieties of predators to infest the Tangle, and compleated many elves — \nGlissa among them —",
" and turned them into predatory creatures. Beyond this, however, he didn't care for anything else \nexcept for his next meal,",
" and, unlike the other praetors who plotted against each other and Karn, Vorinclex appeared to \nbe satisfied.",
" Being the most content of the praetors, Elesh Norn was able to manipulate him easily once she \ntook over New Phyrexia.",
" Vorinclex was sent to Kaldheim through the Planar Bridge on Norn's orders. The process he undertook \ndestroyed his organic components,",
" leaving a corpse of metal and bone; a curious stag sniffed it, allowing him to rebuild himself. To \nundermine or take over the plane,",
" he ambushed the planeswalker Tibalt and infected him, forcing him to cause 'a distraction' in exchange \nfor an antidote,",
" much to the sadistic pain mage's delight as he had already been planning to cause some chaos on \nKaldheim anyway.",
" He stalked the woods of Bretagard where he compleated people and animals until Kaya and the Omenseekers \nfought him.",
" The god Alrund revealed himself, too disgusted at Vorinclex, and the praetor fled, melting into some \noil-suffused metal and escaping,",
" possibly to another of Kaldheim's realms. In the cover of the chaos Tibalt brought to Kaldheim,",
" Vorinclex invaded the sanctum of Esika and mauled her to near death. Taking a tyrite sample,",
" he concluded his mission, and a portal to New Phyrexia opened, welcoming him once more.",
" He returned to New Phyrexia in Norn's throne room in a similar state to how he arrived on Kaldheim.",
" The sample was later used to seed Realmbreaker, the New Phyrexian Invasion Tree. Vorinclex now delegates",
" most of his responsibilities to the compleated elf Glissa. She was an indispensable help when designing \nthe Hunter Maze.",
" When a contingency of planeswalkers led an assault on New Phyrexia, a healed Vorinclex was found \nplayfully sparring with Glissa in the Hunter Maze.",
" Their fight was interrupted by Lukka and Nissa, who attacked them. Vorinclex was severely wounded by Nissa,",
" but a compleated Lukka put Nissa on the run, and Glissa ordered Lukka to capture the elf and compleat \nher for Norn's plans.",
" Vorinclex's Copper Host invaded the Multiverse along with the other Phyrexians, while he stayed back with \nthe other praetors to supervise Realmbreaker.",
" When Elspeth Tirel arrived to help Koth, Chandra, and Wrenn in their attack, Elesh Norn in despair broke \noff one of Vorinclex's",
" horns to throw it at the archangel planeswalker. When Zhalfir was switched with New Phyrexia, Vorinclex \nmet the invading force head-on,",
" forcibly dismounted Teferi before he was decapitated by either Elspeth Tirel or Shella, an Askari knight. However,",
" due to being able to regrow his body (as shown by recovering from his near-destruction using the Planar \nBridge to Kaldheim), his ultimate fate remains to be seen." 

jin_gitaxis = "Jin-Gitaxias, was the blue-aligned praetor of New Phyrexia. He is presumed dead, devoured by his own larvae.",
" When the Phyrexians infected Mirrodin, it was a world of five suns. The five praetors each rose under the \ninfluence of each sun.",
" Jin-Gitaxias was influenced by blue mana, so he searched for knowledge. He grabbed everything he could and improved on it.",
" He was cold, brutal, and believed he was the smartest of the praetors. Jin-Gitaxias' enormous body was made of chrome,",
" with clawed arms and a curved spine. Exposed ribs and pointed vertebrae were displayed like metalwork.",
" His face and mouth were monstrous and bird-like, with too many sharp points and long, flat teeth.",
" His voice sounded like metal grating against metal. Obsessed with perfecting Phyrexia to its highest potential,",
" he was the author of a revisionist philosophy known as 'Great Synthesis',",
" which takes some liberties with Phyrexia's core religious philosophy to make progress easier. For instance,",
" he saw the original Father of Machines as ultimately imperfect (the same applied to the later leader),",
" and discarded the term 'evolution' when applied to Phyrexia as he felt it an inappropriate term to",
" describe what was occurring (as well as to distinguish his views of perfection from those of Vorinclex and Glissa).",
" Living in what was once the Lumengrid, he tended a large variety of newts that grew in vats attached to \nnearly every place in the facilities.",
" His interest in perfection and natural curiosity led him to explore the occult, and it was implied that he \ncould make use of White and Black mana.",
" Using Sheoldred's necromantic prophetic visions, he had access to many creature designs he could turn his \nnewts into.",
" He hated Vorinclex and considered Karn too incompetent to rule. He once captured Tezzeret, and brought him \nbefore Karn.",
" Although Elesh Norn was aware of his machinations, Jin-Gitaxias appeared to keep at least a neutral relationship \ntowards her until the end."


urabrask = "Urabrask, 'the Hidden', was the red-aligned praetor of New Phyrexia.",
" The most mysterious praetor in the beginning, his continual defiance of the New Phyrexian leadership gave \nthe Mirran resistance",
" the chance they needed to eventually bring the fall of Elesh Norn. He is presumed dead following New \nPhyrexia's Invasion of the Multiverse.",
" Urabrask had a blazing-hot temper and was easily infuriated when dealing with others. Much less formal \nthan Phyrexians like Elesh Norn,",
" he was known to be sarcastic and even sassy. He often injected slang and modified words into his speech,",
" expecting his followers to understand his meaning. Physically, Urabrask was serpentine, with a long tail \nand powerful limbs.",
" His head was eyeless, its most notable feature being a crocodilian mouth filled with jagged teeth.",
" Urabrask was constantly upgrading himself; it's unclear if any of his original form remained. As of his \ntravel to New Capenna,",
" he had upgraded his body with large, metallic blades on his forearms. Upon his return to New Phyrexia, his \nbody was streamlined,",
" redesigned to be more combat-ready and aggressive. His body glowed with internal heat,",
" which was vented from two exhaust ports protruding from his back. Like other praetors,",
" Urabrask believed the compleation of living beings elevates them into a more perfect Phyrexian form.",
" As one of the more intelligent red-aligned Phyrexians, however, he retained a sense of individualism and \nsome empathy.",
" Unlike the other praetors who forced new recruits into their designs,",
" Urabrask preferred they retain the strongest parts of their original form and contribute these assets to \nPhyrexia.",
" Secretly, he preferred when beings willingly chose to join New Phyrexia, but he was not above destroying \nthose who opposed it.",
" Urabrask opposed the strictly hierarchical leadership of New Phyrexia. Similarly to Jin-Gitaxias,",
" philosophical differences led to him coining a new term for Yawgmoth's Grand Evolution: The Great Work."

sheoldred = "Sheoldred, known as the Whispering One was the Praetor of the Black Faction of the Phyrexian \nInvasion on Mirrodin.",
" As part of New Phyrexia's Invasion of the Multiverse, she was captured by Elesh Norn's forces and beheaded \nby Ajani Goldmane.",
" The black-aligned faction, led by Sheoldred, had one goal: enslave. Believers would serve. Unbelievers \nwould be made to serve.",
" All would bow to Phyrexia.Sheoldred appeared as a feminine humanoid torso emerging from a huge-mouthed, \nmany-jointed fiend.",
" Her movements were spiderlike in their grace, her limbs finding purchase among the mycosynth and metallic \nstructures of the Core.",
" Her body was covered with plates of oily, corroded metal. Her voice was a soft, grinding whisper, and she \nwas kept informed at all times by a constant stream of informants,",
" spies, and underlings. Sheoldred could separate her body into two pieces. Her relatively humanoid torso was \nlocked into an access inlet built into her monstrous lower half.",
" Though few had seen it happen, Sheoldred could shed her large, predatory, more motile lower body and \nslither-skitter to a new home.",
" While connected to her lower body, she spoke through its mouth. She was graceful, cruel, and the cleverest \nof the thanes.",
" Her tactics were primarily covert and underhanded, frequently leveraging lies or misinformation.",
" She earned her praetor position by manipulating the other thanes against each other. She hid her knowledge \nin irregular,",
" whispering puzzle boxes known as 'astral coffers'. Sheoldred's philosophy was the closest to Old Phyrexia \nof the praetors.",
" Sheoldred believed in acquiring power through any means necessary. One of her main tools was the creation \nof sleeper agents."

gix = "Gix was a Phyrexian demon and praetor who served as one of the highest-ranking lieutenants to the Dark God Yawgmoth.",
" Originally a human Thran from the continent of Terisiare on the plane of Dominaria, Gix was converted into a \nPhyrexian Demon by Yawgmoth himself during the events of the Thran-Phyrexian War.",
" His demon body was built of bone, machine parts, and soft meat. Gix first appeared during the final years of ",
" the ancient Thran Empire as a human rebel operating out of the Caves of the Damned, a network of tunnels beneath \nthe Thran capital that served as home to the outcasts of Thran society.",
" Most of these outcasts, including Gix, suffered from a deadly sickness known as phthisis, which was caused by \nradiation from powerstones,",
" the very energy source that fueled the Thran Empire and all its technological advancements. Channeling the anger \nand resentment of the outcasts,",
" Gix ambushed and attempted to assassinate Glacian, the genius Thran artificer who had pioneered powerstone technology.",
" He stabbed Glacian with a powerstone shard, thus infecting him with the same radiation sickness that afflicted \nthe outcasts in the Caves of the Damned.",
" As Glacian's health deteriorated over the next few years, his wife, the Thran architect Rebbec, summoned the exiled \nmedical prodigy Yawgmoth back to the capital to treat him.",
" During this time, Gix led multiple violent uprisings in the capital, but in the end, his rebellion was pacified by Yawgmoth,",
" who finally devised a cure for phthisis and offered to share it with the sick inhabitants of the Caves of the \nDamned. Using the cure as leverage,",
" Yawgmoth was able to coerce an oath of loyalty from Gix, who, in return for the phthisis cure (and his life), \nvowed to serve Yawgmoth faithfully forever.",
" After the founding of Phyrexia by Yawgmoth, Gix became one of the first living beings to be Compleated,",
" shucking aside his humanity to become a Phyrexian monstrosity and rising to serve as Yawgmoth's right-hand man \nthroughout the Thran-Phyrexian War.",
" At the conclusion of the War, he was banished from Dominaria along with all of Yawgmoth's minions,",
" trapped on the mechanical plane of Phyrexia when the Thran architect Rebbec closed the portal connecting \nPhyrexia to Dominaria.",
" The Thran Empire collapsed in the War's aftermath, but Yawgmoth, Gix, and the other Phyrexians remained sealed \naway from Dominaria for eons.",
" Augmenting themselves with machinery and dark technology, the Phyrexians transcended their former mortal \nlifespans. Over the millennia that followed,",
" Gix became a powerful demon and praetor while his master, Yawgmoth, ascended to become a god deep within \nthe core of the plane."

yawgmoth = "Yawgmoth, in phyrexian language known as 'Machine Father', also known as The Ineffable to his servants,",
" and referred to as The Lord of the Wastes throughout Dominarian mythology, was the god and perfector of \nthe Phyrexian race."
" Originally human, in his early life, he was a medical genius of the ancient Thran Empire known for his \nhighly controversial solutions",
" to medical ailments.While still human, Yawgmoth discovered an abandoned,",
" artificial plane created by a deceased planeswalker and seized the opportunity to utilize that mechanical \nworld to his ends.",
" He took control of that plane and became its god, naming the world 'Phyrexia' but his true dream was to return",
" to his home plane of Dominaria and turn its inhabitants into 'perfect beings' under his rule.",
" As the main antagonist throughout multiple Magic: The Gathering sagas, he is one of the most well-known \nvillains in the game's entire story."
" Yawgmoth was born in the last century of the ancient Thran Empire, during a highly politicized conflict \nbetween the",
" artificer-aligned elite imperialists and the eugenicist-aligned republican rabble. Due to his fascination \nwith the human body",
" and his view that it was a marvelous machine, Yawgmoth became a champion of the eugenicist faction. \nUnfortunately for him,",
" after the republicans were defeated, all of their eugenicist champions were blamed and exiled along \nwith their followers.",
" In The Thran, he is described as being a tall, muscular (due to past rigorous work), human, with thick,",
" dark black hair that created a natural visor for his face. He is thirty-five years old when first introduced,",
" returning from exile to meet Rebbec at the gates of the Thran capital, Halcyon.After five years in exile,",
" Yawgmoth was suddenly recalled to the Thran capital of Halcyon, where the people remained unaware of \nhis inhumane actions.",
" A high-profile medical emergency had recently shaken the capital: Glacian, the chief artificer and \ntechnological genius of the Thran Empire,",
" had been attacked and stabbed with a powerstone, after which he had caught a strange disease impervious \nto Thran healing magic.",
" With nowhere else to turn for help, Glacian's wife Rebbec used her influence as chief architect to \nbring Yawgmoth back,",
" hoping his expertise in eugenics could find a cure.Yawgmoth's medical expertise quickly bore fruit.",
" He discovered that Glacian's disease, which he called phthisis, was caused by extensive exposure to \npowerstone radiation",
" - the very energy source that powered Thran's advanced civilization. Most of the Untouchables \n(exiled Thran who lived in the Caves of the Damned,",
" beneath the power stone-producing Mana Rig) had also caught the disease. Upon hearing this, the man \nwho had stabbed Glacian,",
" Gix, started rallying his fellow Untouchables to rebel and take vengeance upon the Thran.",
" Yawgmoth convinced Halcyon's elders to give him more funding and apprentices to study the disease.",
" The healer Xod gave him the idea to use metals to create a serum against phthisis. When Gix and his \nsupporters came to Halcyon,",
" planning to start a massive rebellion, Yawgmoth managed to quell it by offering free serum to the \nUntouchables. For his actions,",
" Yawgmoth was made a member of the council of Halcyon and was allowed to make laws to regulate public health.",
" Yawgmoth started sending infected people down into the Caves of the Damned and had healthy \nUntouchables return to the city,",
" using this to eliminate his enemies from the city. During this time, Rebbec and Yawgmoth \nstarted falling in love,",
" although neither of them acted deeply upon it, It was eventually discovered that Yawgmoth was \ndiluting the serum he gave to the Untouchables,",
" claiming a lack of resources. This caused Gix to feel rebellious again, and he started to send \nUntouchables, both healthy and sick,",
" up to Halcyon. Yawgmoth used this development to attain more funding and complete control over \nthe Halcyte Guard. One day,",
" the planeswalker Dyfed visited Glacian, wanting to meet the genius in real life, and also to \nlearn about his spark,",
" though she said nothing of it. Yawgmoth walked in on the meeting and managed to talk Dyfed into \naiding him.",
" Dyfed agreed to find a plane where Yawgmoth could build his paradise. When Gix led another large \nriot in the city, Yawgmoth was prepared.",
" He made an artifact, based on Glacian's designs, to control all powerstone technology in the \ncity. With it and the Halcyte Guard,",
" he managed to stop the invasion and force Gix into complete obedience. After the city had been \nrebuilt,",
" Halcyon held a great festival to honor Yawgmoth, but a strange group of delegates appeared shortly \nbefore it could commence.",
" They were representatives of the nations Yawgmoth 'experimented on' during his exile and they came \nto declare war on all who stood by Yawgmoth.",
" Faced with the threat of a full-scale war with the united nations, the Thran council voted on \nwhether Yawgmoth could stay,",
" but the votes went 50/50. It came down to the last two members of the council; Yawgmoth and \nRebbec themselves,",
" voting together to ensure Yawgmoth's safety in the city. He immediately overthrew the council \nand imprisoned its elders,",
" as well as the delegates. Sometime later, Dyfed opened a permanent portal from Dominaria to Phyrexia,",
" the plane which Yawgmoth wanted to make his paradise. Yawgmoth bound himself to the plane within \nits core,",
" becoming a god while staying there. He started to bring phthisis patients to Phyrexia,",
" where they were implanted with empty powerstones that drained away their sickness. The patients \nslowly began to evolve as well,",
" growing longer, thinner, stronger, and faster. Yawgmoth hid the two halves of the powerstone \nDyfed cracked to power the portal inside Glacian's wounds.",
" Yawgmoth fared quite well while warring with the alliance of nations against him. Using the \nHalcyte Guard,",
" soldiers mutated in Phyrexia, and stonechargers, he could overcome any army that stood against \nhim. Even when Dyfed turned on him, he did not give in.",
" When she was stunned at the horror Phyrexia had become, he stabbed her in the back of the head \nwith a powerstone dagger,",
" disabling the planeswalker, hoping to dissect her and learn what she had that enabled her to \nplaneswalk.",
" Rebbec removed the powerstone however, mercy-killing Dyfed. But not all went well for him.",
" He had used the Null Sphere to filter away the deadly gasses left behind by the stonechargers \nbefore they reached Halcyon.",
" When the artificers that controlled it sacrificed their own lives to sabotage the Sphere,",
" Halcyon was destroyed, all its inhabitants fleeing to Phyrexia or being eaten away.",
" Yawgmoth had planned to stay in Phyrexia for a while and emerge again when the death cloud had lifted,",
" but Rebbec had finally seen what a monstrosity he was and used the powerstones Yawgmoth had \nplanted in her husband to close the portal between Phyrexia and Dominaria,",
" locking Yawgmoth and his followers out for all eternity. Or so she hoped. For ages,",
" Yawgmoth continued to alter the Thran that had come to Phyrexia while fleeing the fallout of \nthe stonechargers,",
" transforming them into the first true Phyrexians. Using planar portals, the Phyrexians journeyed \nto many planes which they conquered,",
" while they used its inhabitants as raw material for the Newts, as Phyrexians who had not been \naugmented were known.",
" But Yawgmoth was not happy, for somehow Rebbec had completely locked him out of Dominaria.",
" Then came the day the archeologist brothers Urza and Mishra disturbed the powerstone sealing \nthe portal while exploring the Caves of the Damned,",
" now known as the Caves of Koilos. Yawgmoth sent Gix, now a fully compleated Phyrexian and a \nmember of his Inner Circle,",
" through the portal as a scout. Gix planned to manipulate the Brothers, who had started a war. \nHaving his minions,"
" the Brotherhood of Gix, infiltrate both sides and eventually replacing Mishra with a Phyrexian,",
" Gix hoped to magnify the war until it had destroyed all civilization on the continent,",
" allowing for a simple infiltration by the Phyrexian Forces built up by Yawgmoth over the centuries.",
" During the war's end, Urza activated the Golgothian Sylex, an artifact so powerful it \ncompletely devastated the world of Dominaria.",
" Gix fled back to Phyrexia, telling Yawgmoth of what had happened. Gix's plans to infiltrate \nDominarian society via the Sleeper Agents were approved by the dark god,",
" but the first few attempts failed since all the Agents looked alike. The sudden appearance of \nmany people looking",
" exactly similar had caused panic among the Dominarians, who proceeded to kill any they came \nacross. Gix planned to try again,",
" but by then the Shard of the Twelve Worlds was completed. The Shard had been a side effect of \nthe Sylex Blast:",
" it locked twelve worlds from the other planes of the multiverse, trapping many planeswalkers inside,",
" but also keeping the Phyrexians outside. A furious Yawgmoth had Gix thrown into the 7th Sphere \nof Phyrexia,"
" where he would be tortured for all eternity. Then Urza, who had died in the blast, but was \nreborn a planeswalker,"
" attacked Phyrexia. Moments before he activated the Sylex, Urza discovered his brother had been \nturned into a machine",
" and had gone completely insane, blaming those responsible for turning his brother into a machine \nfor all the wrongs of the Brothers' War.",
" To add more fire to his hate, Urza's eyes had been replaced with the Mightstone and the Weakstone,",
" the two halves of the powerstone that contained Glacian's spirit. Having met the Newt Xantcha,",
" who had been intended as a Sleeper Agent but had been turned into an expendable servant now \nthat the Agents couldn't be deployed,"
" Urza had discovered Phyrexia was responsible and had created a monstrous machine-dragon to \nattack the plane."
" He managed to blast a gigantic hole in the plane, all the way down to the 4th Sphere, but then \nYawgmoth himself invaded his mind and made him go even more insane.",
" Urza fled and for years he traveled from plane to plane, the Phyrexians always on his heels,",
" for Yawgmoth couldn't let someone who planned to destroy Phyrexia go unpunished. Urza was \neventually healed by Serra,",
" but after he left the Phyrexians even invaded her realm and corrupted it. Then Freyalise, \ndesperate to be free from the Shard,",
" cast the World Spell, opening Dominaria to Yawgmoth once again. He released Gix from his \ntorment since he knew",
" more about fighting Urza and infiltrating Dominaria than anyone else, but while Gix was initially \nsuccessful Urza returned to his homeplane as well."
" He first destroyed all Sleeper Agents and then killed Gix. In the wake of his latest setback,",
" Yawgmoth set about concocting a different plan: instead of infiltrating Dominaria,",
" he would prepare for a full-blown invasion. He started to amass an army and created the artificial \nplane of Rath,",
" which he planned to fill with troops and then merge with Dominaria, placing all his forces \nthere in a single moment.",
" Even as he set his new plan into motion, Yawgmoth continued to send troops after Urza, \nrecognizing him as one of the greatest threats to his plans.",
" One of the more successful ones was K'rrik, a Sleeper Agent who tracked down Urza's academy \non Tolaria,",
" where mages were trained and artifacts were built to fight Phyrexia. K'rrik succeeded in \ndestroying the place,",
" but Urza sent the silver golem Karn back in time to prevent this. He succeeded,",
" but the time machine overheated and destroyed the academy nonetheless.",
" When Urza returned ten years later he found that the time streams of the island had been \ntwisted. In some places,",
" ten thousand years happened in a single second, in others, it was the other way around. \nTrapped inside a fast-time bubble,",
" K'rrik had ages to prepare for an attack on Urza, but the planeswalker eventually managed to",
" defeat him with the help of the nature spirit Multani. While the evincars of Rath started \nto overlay small parts of the plane with Dominaria",
" in preparation for the coming invasion, the artificial plane filled up with beings from \nDominaria and other planes on which the Phyrexians could experiment.",
" Among them were the Kor, humans with strange elongated skulls. When the Inner Circle member Croag,",
" who oversaw the progress of the plane, discovered humans with Phyrexian traits in them in Benalia,",
" the truth about the Kor was revealed: Urza had started the Bloodline project,",
" a grand plan to manipulate the breeding patterns of several groups of Dominarians to create \nperfect warriors to fight Phyrexia.",
" The project resulted in ordinary humans with an affinity for tracking down and fighting \nPhyrexians, and in the Metathran,",
" genetically engineered warriors with no will of their own, eerily similar to the Phyrexians \nthey were designed to fight.",
" After discovering this, Yawgmoth increased the raids on Dominaria, tracking down the Bloodline \nresults and killing them.",
" Croag devastated the nation of Keld, where the renegade Bloodline researcher Gatha had created \nhumans like Kreig,",
" who were able to severely wound an Inner Circle member. Despite Yawgmoth's efforts, some \nBloodline children slipped through the attacks,",
" such as Gerrard, the true heir to Urza's Legacy, a collection of artifacts made for the \nsingle purpose of destroying Yawgmoth.",
" The attacks became so frequent at times that they started to play a role in local myths. Stories \nabout the Lord of the Wastes,",
" a machine lord who waged eternal war on Dominaria, started to spread from Benalia to Jamuraa. \nAfter many centuries of preparation,",
" Yawgmoth finally launched his full-scale invasion of Dominaria in 4205 AR. Throughout most of \nthe invasion,",
" Yawgmoth remained within the depths of Phyrexia while his minions Crovax and Tsabo Tavoc \ncommanded the Phyrexian armies in battle.",
" Tsabo Tavoc's plagues and shock troops devastated numerous Dominarian nations,",
" while Crovax oversaw the overlay of the plane of Rath onto Dominaria, bringing millions of \nadditional Phyrexian",
" soldiers and monstrosities to assault the beleaguered world. Yet even as Phyrexia wore down \nDominaria’s nations,",
" the defenders managed to fight for months on end, delaying Phyrexia’s victory. In the face \nof continued resistance,",
" Yawgmoth became convinced that his ultimate foe was not Urza, but the living spirit of \nRebbec herself,",
" who he believed had somehow survived the destruction of the Thran and ascended to become \nthe Dominarian worldsoul, Gaea.",
" As Dominaria struggled, Yawgmoth sensed Rebbec resisting him even still, determined to shut \nhim out of Dominaria for eternity.",
" Yawgmoth's darkness fills the skies as he returns to Dominaria at last. In the last hours \nof the war,",
" Yawgmoth finally returned to Dominaria for the first time in 9000 years. He did so in the \nform of a black,",
" world-spanning death cloud that killed Dominaria's defenders and resurrected them to fight \nfor Phyrexia.",
" But there was still hope for the plane: even as Yawgmoth's black spirit wrapped around the \nentire world and prepared to crush it in his grasp,",
" Urza and Gerrard hovered high overhead in the skyship Weatherlight, the main part of the \nLegacy.",
" They punctured the Null Moon itself and collected the white mana it had been gathering \nthere for millennia,",
" ever since the Thran artificers of old had launched it into the sky and caused Yawgmoth's \nfirst defeat.",
" Yawgmoth tried to flee back to Phyrexia, but the Stone Druids had activated the volcano \nunder the Stronghold,",
" covering the only remaining portal to Phyrexia in deep magma. Yawgmoth was hurt by the \nwhite mana but survived.",
" Seeing the Weatherlight transfigured and wreathed in beaming white mana like a divine being,",
" Yawgmoth no longer recognized it as Urza's skyship but instead perceived it to be the \nsoul of Rebbec,",
" the protector of Dominaria and his opposite. Resolving to possess and destroy Rebbec at last,",
" Yawgmoth summoned a storm of giant black tentacles that erupted from the black clouds and \nattacked the Weatherlight.",
" Undeterred, Gerrard took out Urza's gemstone eyes - the two halves of the powerstone that \nhad locked out Yawgmoth and",
" contained the spirit of Glacian - and placed them in the cavities in Karn's chest, \ncompleting the Legacy.",
" The exact working of the Legacy device is unknown, but it created a sentient light that \nexploded from the Weatherlight",
" and dissolved Yawgmoth's death-cloud form, killing him at last. 101 years later, the \ngodlike being Karona was looking for",
" other beings like her. She first summoned a 'god' for each color of magic, and the black \none appeared to be Yawgmoth.",
" Later she traveled across the planes and ended up in Phyrexia, devastated by the Nine Titans, \nbut still holding together.",
" There she met a disembodied voice claiming to be Yawgmoth, suggesting that he was still alive \nand needed her help to rebuild.",
" However, subsequent canon sources have explicitly confirmed Yawgmoth's death, and given \nKarona's unstable nature,",
" this supposed encounter was likely just a manifestation of her warped psyche. Alternatively, \nthe whispering voice",
" might have been a lingering echo or faded memory of the dead god's former power in Phyrexia. \nGiven Karona's",
" near-omnipotence and unique power to shape reality, it's conceivable that she alone might \nhave been able to resurrect",
" Yawgmoth and restore his broken plane had she truly wished. In any case, she declined \nto do so,",
" recoiling in horror from Phyrexia and fleeing its shattered husk." 


phyrexians = {
        "Elesh Norn" :{
        "card" : "Mother of Machines, Grand Cenobite, the white Praetor",
        "lore" : elesh_Norn,
        },
        "Vorinclex" :{ 
        "card" : "Voice of Hunger, Monstrous Raider, the green Praetor",
        "lore" : vorinclex,
        },
        "Jin Gitaxis" :{ 
        "card" : "Progress Tyrant, Core Augur, the blue Praetor",
        "lore" : jin_gitaxis,
        },
        "Urabrask" :{
        "card" : "The Hidden, Heretic Praetor, the red Praetor",
        "lore" : urabrask,
        },
        "Sheoldred" :{ 
        "card" : "Whispering one, the Apocaplypse, the current black praetor",
        "lore" : sheoldred,
        },
        "Gix" : {
        "card" : "Yawgmoth Praetor, The original phyrexian praetor personally created by yawgmoth himself as well as the first black praetor",
        "lore" : gix,
        },
        "Yawgmoth":{
        "card" : "thran physician, also The Father of Machines the Innefable and the lord of the wastes, however these additional names are not on any cards, you'll want to read his lore for it to make sense.",
        "lore" : yawgmoth,
        },
}

